
version: '3.9'
services:
  fe-dev:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:8001}
      - VITE_API_ROLE_IS_NUMERIC=${VITE_API_ROLE_IS_NUMERIC:-true}
    ports:
      - "5173:5173"
    command: sh -lc "npm i && npm run dev -- --host"
  fe-prod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://localhost:8001}
    ports:
      - "8081:80"
